import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "../components/layout/Nav";
import Footer from "../components/layout/Footer";
import { log } from "console";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`bg-gradient-to-br from-[#f5e9e0] via-[#d2c8c1] to-[#ddc1ae]`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
